# Generated by Django 4.1.3 on 2022-11-18 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_isactive'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Ulanyjy', 'verbose_name_plural': 'Ulanyjylar'},
        ),
        migrations.AlterField(
            model_name='user',
            name='isComment',
            field=models.BooleanField(default=True, verbose_name='Kommentariya Yazsynmy'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_no',
            field=models.CharField(max_length=15, verbose_name='Telefon Nomeri'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, unique=True, verbose_name='Ulanyjy ady'),
        ),
        migrations.AlterField(
            model_name='user',
            name='velayat',
            field=models.CharField(choices=[('Balkan', 'balkan'), ('Ahal', 'ahal'), ('Mary', 'mary'), ('Lebap', 'lebap'), ('Dashoguz', 'dashoguz'), ('Ashgabat', 'ashgabat')], max_length=10, verbose_name='Welayat'),
        ),
    ]
