# Generated by Django 3.2.16 on 2022-10-18 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('un', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.ImageField(upload_to='images')),
                ('image_2', models.ImageField(upload_to='images')),
                ('region', models.CharField(choices=[('yaslyk', 'Ýaşlyk'), ('akbugday', 'Ak bugdaý'), ('baherden', 'Bäherden'), ('babadayhan', 'Babadaýhan'), ('gokdepe', 'Gökdepe'), ('kaka', 'Kaka'), ('anew', 'Änew'), ('tejen', 'Tejen'), ('sarahs', 'Sarahs'), ('magtymguly', 'Magtymguly'), ('bereket', 'Bereket'), ('etrek', 'Etrek'), ('esenguly', 'Esenguly'), ('gumdag', 'Gumdag'), ('garabogaz', 'Garabogaz'), ('balkanabat', 'Balkanabat'), ('hazar', 'Hazar'), ('serdar', 'Serdar'), ('turkmenbasy', 'Türkmenbaşy'), ('jebel', 'Jebel'), ('yoloten', 'Ýolöten'), ('mary', 'Mary'), ('murgap', 'Murgap'), ('sakarcage', 'Sakarçäge'), ('serhetabat', 'Serhetabat'), ('tagtabazar', 'Tagtabazar'), ('turkmengala', 'Türkmengala'), ('oguzhan', 'Oguz han'), ('satlyk', 'Şatlyk'), ('bayramaly', 'Baýramaly'), ('wekilbazar', 'Wekilbazar'), ('garagum', 'Garagum'), ('darganata', 'Darganata'), ('farap', 'Farap'), ('gazojak', 'Gazojak'), ('danew', 'Dänew'), ('garabekewul', 'Garabekewül'), ('turkmenabat', 'Türkmenabat'), ('dostluk', 'Dostluk'), ('hojambaz', 'Hojambaz'), ('koytendag', 'Köýtendag'), ('magdanly', 'Magdanly'), ('kerki', 'Kerki'), ('sakar', 'Sakar'), ('sayat', 'Saýat'), ('seydi', 'Seýdi'), ('carjew', 'Çärjew'), ('halac', 'Halaç'), ('akdepe', 'Akdepe'), ('gurbansoltaneje', 'Gurbansoltan Eje'), ('boldumsaz', 'Boldumsaz'), ('gubadag', 'Gubadag'), ('dasoguz', 'Daşoguz'), ('gorogly', 'Görogly'), ('turkmenbasy', 'Türkmenbaşy'), ('ruhubelent', 'Ruhubelent'), ('koneurgenc', 'Köneürgenç'), ('sanyyazow', 'S.A. Nyýazow')], max_length=50)),
                ('reg', models.CharField(choices=[('default', 'Ulanyjy'), ('market', 'Market'), ('service', 'Hyzmat')], max_length=50)),
                ('code', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=400)),
                ('warning', models.TextField()),
                ('place', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('about', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='markets.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Market',
                'verbose_name_plural': 'Marketler',
            },
        ),
    ]
