# Generated by Django 4.1.3 on 2022-12-03 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0002_alter_category_name_alter_category_un_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, verbose_name='Ady')),
                ('price', models.CharField(max_length=200, verbose_name='Bahasy')),
                ('about', models.TextField(verbose_name='Hakynda')),
                ('image', models.ImageField(upload_to='images', verbose_name='Surat 1')),
                ('date', models.DateField(auto_now=True, verbose_name='Senesii')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='markets.market', verbose_name='Hyzmat')),
            ],
            options={
                'verbose_name': 'Hyzmat',
                'verbose_name_plural': 'Hyzmatlar',
            },
        ),
    ]
