# Generated by Django 4.1.3 on 2022-12-22 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('markets', '0004_servicefavourite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='market', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Ulanyjy'),
        ),
    ]
