# Generated by Django 4.1.3 on 2022-12-24 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0005_alter_market_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='warning',
            field=models.TextField(verbose_name='Duýduryş teksti'),
        ),
    ]
