# Generated by Django 3.2.16 on 2022-10-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.ImageField(upload_to='images')),
                ('image_2', models.ImageField(upload_to='images')),
                ('image_3', models.ImageField(upload_to='images')),
                ('body', models.TextField()),
                ('link', models.URLField()),
                ('category', models.CharField(choices=[('teachers', 'Mugallymlar we okuwçylar'), ('students', 'Içerki daşarky Talyplar'), ('masters', 'Ussatlar'), ('internet', 'Internet'), ('jokes', 'Degişmeler')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
