# Generated by Django 4.1.3 on 2022-11-18 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breaktime', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'verbose_name': 'Arakesme tekst', 'verbose_name_plural': 'Arakesme tekstler'},
        ),
        migrations.AlterField(
            model_name='content',
            name='body',
            field=models.TextField(verbose_name='Teksti'),
        ),
        migrations.AlterField(
            model_name='content',
            name='category',
            field=models.CharField(choices=[('teachers', 'Mugallymlar we okuwçylar'), ('students', 'Içerki daşarky Talyplar'), ('masters', 'Ussatlar'), ('internet', 'Internet'), ('jokes', 'Degişmeler')], max_length=50, verbose_name='Kategoriýa'),
        ),
        migrations.AlterField(
            model_name='content',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Wagty'),
        ),
        migrations.AlterField(
            model_name='content',
            name='image_1',
            field=models.ImageField(upload_to='images', verbose_name='Surat 1'),
        ),
        migrations.AlterField(
            model_name='content',
            name='image_2',
            field=models.ImageField(upload_to='images', verbose_name='Surat 2'),
        ),
        migrations.AlterField(
            model_name='content',
            name='image_3',
            field=models.ImageField(upload_to='images', verbose_name='Surat 3'),
        ),
        migrations.AlterField(
            model_name='content',
            name='link',
            field=models.URLField(verbose_name='Link'),
        ),
    ]
