# Generated by Django 4.1.3 on 2022-12-24 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breaktime', '0002_alter_content_options_alter_content_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Surat 2'),
        ),
        migrations.AlterField(
            model_name='content',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Surat 3'),
        ),
    ]
