# Generated by Django 3.2.16 on 2022-10-17 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('breaktime', '0002_comment_for_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites_Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='breaktime.content')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_contents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
