# Generated by Django 3.2.16 on 2022-10-13 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('image', models.ImageField(upload_to='images')),
                ('link', models.URLField()),
                ('category', models.CharField(choices=[('onumchilik', 'Önümçilik'), ('sowda', 'Söwda'), ('okuw', 'Okuw'), ('habar', 'Habar')], max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('isComment', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
