# Generated by Django 4.1.3 on 2022-11-18 03:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'verbose_name': 'Bildiriş', 'verbose_name_plural': 'Bildirişler'},
        ),
        migrations.AlterField(
            model_name='notice',
            name='body',
            field=models.TextField(verbose_name='Teksti'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='category',
            field=models.CharField(choices=[('onumchilik', 'Önümçilik'), ('sowda', 'Söwda'), ('okuw', 'Okuw'), ('habar', 'Habar')], max_length=50, verbose_name='Kategoriýa'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Wagty'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='image',
            field=models.ImageField(upload_to='images', verbose_name='Surat'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='isComment',
            field=models.BooleanField(default=True, verbose_name='Kommentariya yazyp bilsinlermi'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Aktiw'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='link',
            field=models.URLField(verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to=settings.AUTH_USER_MODEL, verbose_name='Ulanyjy'),
        ),
    ]
