# Generated by Django 4.1.3 on 2022-11-18 03:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorites',
            options={'verbose_name': 'Halanlarym', 'verbose_name_plural': 'Halanlarym'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Sapak', 'verbose_name_plural': 'Sapaklar'},
        ),
        migrations.AlterField(
            model_name='favorites',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.lesson', verbose_name='Sapagy'),
        ),
        migrations.AlterField(
            model_name='favorites',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='Ulanyjy'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='category',
            field=models.CharField(choices=[('english', 'Inlis Dili'), ('russian', 'Rus Dili'), ('chinese', 'Hytay dili'), ('turkish', 'Turk dili')], max_length=30, verbose_name='Kategoriýasy'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='language',
            field=models.CharField(choices=[('english', 'Inlis Dili'), ('russian', 'Rus Dili'), ('chinese', 'Hytay dili'), ('turkish', 'Turk dili'), ('turkmen', 'Turkmen Dili')], max_length=30, verbose_name='Öwredýän dili'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='link1',
            field=models.URLField(blank=True, verbose_name='Video link 1'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='link2',
            field=models.URLField(blank=True, verbose_name='Video link 2'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='link3',
            field=models.URLField(blank=True, verbose_name='Video link 3'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Ady'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='word1',
            field=models.CharField(blank=True, max_length=30, verbose_name='Video söz 1'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='word2',
            field=models.CharField(blank=True, max_length=30, verbose_name='Video Söz 2'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='word3',
            field=models.CharField(blank=True, max_length=30, verbose_name='Video Söz 3'),
        ),
    ]
