# Generated by Django 4.1.3 on 2022-12-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0002_alter_favorites_options_alter_lesson_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='language',
            field=models.CharField(choices=[('english', 'Inlis Dili'), ('russian', 'Rus Dili'), ('chinese', 'Hytay dili'), ('turkish', 'Turk dili'), ('turkmen', 'Turkmen Dili')], max_length=30, verbose_name='Esasy dili'),
        ),
    ]
