# Generated by Django 3.2.16 on 2022-10-12 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('another_lang', models.CharField(max_length=100)),
                ('turkmen', models.CharField(max_length=100)),
                ('additional1', models.TextField(blank=True)),
                ('additional2', models.TextField(blank=True)),
                ('additional3', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('audio_another', models.FileField(upload_to='words')),
                ('audio_turkmen', models.FileField(upload_to='words')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('another_lang', models.TextField()),
                ('turkmen', models.TextField()),
                ('audio_another', models.FileField(upload_to='words')),
                ('audio_turkmen', models.FileField(upload_to='words')),
                ('image_another', models.ImageField(upload_to='images')),
                ('image_turkmen', models.ImageField(upload_to='images')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_another', models.TextField()),
                ('answer_another', models.TextField()),
                ('question_turkmen', models.TextField()),
                ('answer_turkmen', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('additional1', models.TextField(blank=True)),
                ('additional2', models.TextField(blank=True)),
                ('wrong_text', models.TextField(blank=True)),
                ('audio_question_another', models.FileField(upload_to='words')),
                ('audio_answer_another', models.FileField(upload_to='words')),
                ('audio_question_turkmen', models.FileField(upload_to='words')),
                ('audio_answer_turkmen', models.FileField(upload_to='words')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='setting.lesson')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='lesson.comment')),
            ],
        ),
    ]
