# Generated by Django 4.1.3 on 2022-11-18 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0002_alter_favorites_options_alter_lesson_options_and_more'),
        ('lesson', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dialog',
            options={'verbose_name': 'Geplesik', 'verbose_name_plural': 'Geplesikler'},
        ),
        migrations.AlterModelOptions(
            name='text',
            options={'verbose_name': 'Tekst', 'verbose_name_plural': 'Tekstler'},
        ),
        migrations.AlterModelOptions(
            name='word',
            options={'verbose_name': 'Söz', 'verbose_name_plural': 'Sözler'},
        ),
        migrations.AlterField(
            model_name='dialog',
            name='additional1',
            field=models.TextField(blank=True, verbose_name='Goşmaça 1'),
        ),
        migrations.AlterField(
            model_name='dialog',
            name='additional2',
            field=models.TextField(blank=True, verbose_name='Goşmaça 2'),
        ),
        migrations.AlterField(
            model_name='dialog',
            name='answer_another',
            field=models.TextField(verbose_name='Jogap Beýleki dil'),
        ),
        migrations.AlterField(
            model_name='dialog',
            name='answer_turkmen',
            field=models.TextField(verbose_name='Jogap Türkmençe'),
        ),
        migrations.AlterField(
            model_name='dialog',
            name='audio_answer_another',
            field=models.FileField(upload_to='words', verbose_name='Ses Jogap Beýleki dil'),
        ),
        migrations.AlterField(
            model_name='dialog',
            name='audio_answer_turkmen',
            field=models.FileField(upload_to='words', verbose_name='Ses Jogap Türkmençe'),
        ),
        migrations.AlterField(
            model_name='dialog',
            name='audio_question_another',
            field=models.FileField(upload_to='words', verbose_name='Ses Sorag Beýleki dil'),
        ),
        migrations.AlterField(
            model_name='dialog',
            name='audio_question_turkmen',
            field=models.FileField(upload_to='words', verbose_name='Ses Sorag Türkmençe'),
        ),
        migrations.AlterField(
            model_name='dialog',
            name='description',
            field=models.TextField(blank=True, verbose_name='Düşündirilişi'),
        ),
        migrations.AlterField(
            model_name='dialog',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.lesson', verbose_name='Sapagy'),
        ),
        migrations.AlterField(
            model_name='dialog',
            name='question_another',
            field=models.TextField(verbose_name='Sorag Beýleki dil'),
        ),
        migrations.AlterField(
            model_name='dialog',
            name='question_turkmen',
            field=models.TextField(verbose_name='Sorag Türkmençe'),
        ),
        migrations.AlterField(
            model_name='dialog',
            name='wrong_text',
            field=models.TextField(blank=True, verbose_name='Ýalňyş tekst'),
        ),
        migrations.AlterField(
            model_name='text',
            name='another_lang',
            field=models.TextField(verbose_name='Beýlekki dil'),
        ),
        migrations.AlterField(
            model_name='text',
            name='audio_another',
            field=models.FileField(upload_to='words', verbose_name='Ses Beýleki dil'),
        ),
        migrations.AlterField(
            model_name='text',
            name='audio_turkmen',
            field=models.FileField(upload_to='words', verbose_name='SES Türkmençe'),
        ),
        migrations.AlterField(
            model_name='text',
            name='image_another',
            field=models.ImageField(upload_to='images', verbose_name='Surat Beýleki'),
        ),
        migrations.AlterField(
            model_name='text',
            name='image_turkmen',
            field=models.ImageField(upload_to='images', verbose_name='Surat Türkmençe'),
        ),
        migrations.AlterField(
            model_name='text',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.lesson', verbose_name='Sapagy'),
        ),
        migrations.AlterField(
            model_name='text',
            name='turkmen',
            field=models.TextField(verbose_name='Türkmençe'),
        ),
        migrations.AlterField(
            model_name='word',
            name='additional1',
            field=models.TextField(blank=True, verbose_name='Goşmaça 1'),
        ),
        migrations.AlterField(
            model_name='word',
            name='additional2',
            field=models.TextField(blank=True, verbose_name='Goşmaça 2'),
        ),
        migrations.AlterField(
            model_name='word',
            name='additional3',
            field=models.TextField(blank=True, verbose_name='Goşmaça 3'),
        ),
        migrations.AlterField(
            model_name='word',
            name='another_lang',
            field=models.CharField(max_length=100, verbose_name='Beýleki dil'),
        ),
        migrations.AlterField(
            model_name='word',
            name='audio_another',
            field=models.FileField(upload_to='words', verbose_name='Ses Beýleki dil'),
        ),
        migrations.AlterField(
            model_name='word',
            name='audio_turkmen',
            field=models.FileField(upload_to='words', verbose_name='Ses Türkmençe'),
        ),
        migrations.AlterField(
            model_name='word',
            name='description',
            field=models.TextField(blank=True, verbose_name='Düşündirlişi'),
        ),
        migrations.AlterField(
            model_name='word',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.lesson', verbose_name='Sapagy'),
        ),
        migrations.AlterField(
            model_name='word',
            name='turkmen',
            field=models.CharField(max_length=100, verbose_name='Türkmençe'),
        ),
    ]
